
import { Question, QuestionType } from './types';

const cleanUrl = (url: string | undefined): string | undefined => {
    if (!url) return undefined;
    return url.trim()
        .replace(/\s+/g, '')
        .replace(/res\.ioe\.vnzedu/, 'res.ioe.vn/edu')
        .replace(/res\.ioe\.vii/, 'res.ioe.vn')
        .replace(/res\.ioe\.vm/, 'res.ioe.vn')
        .replace(/Audio\s*mp3/i, 'Audio.mp3')
        .replace(/ImageExam\s*(\d)/, 'ImageExam/$1')
        .replace(/Olympic\s*ExamData/, 'OlympicExamData')
        .replace(/EOlympic\s*ExamData/, 'EOlympic/ExamData')
        .replace(/'/g, '')
        .replace(/Audio-mp3/i, 'Audio.mp3');
};

export const QUIZ_DATA: Question[] = [
    { id: 1, type: QuestionType.FILL_IN_BLANK, questionText: "My teacher goes to work by _ _ _ _ .", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/11/30/636161042644282967_566X320.jpg"), correctAnswer: "bike", explanation: "Bike: Xe đạp." },
    { id: 2, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["new", "Is", "your", "school", "big?"], correctAnswer: "Is your new school big?", explanation: "Trường mới của bạn có lớn không?" },
    { id: 3, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["a", "there", "dog?", "Is"], correctAnswer: "Is there a dog?", explanation: "Có con chó nào không?" },
    { id: 4, type: QuestionType.MULTIPLE_CHOICE, questionText: "Give ... that pink crayon.", options: ["he", "she", "me", "the"], correctAnswer: "me", explanation: "Give me: Đưa cho tôi." },
    { id: 5, type: QuestionType.FILL_IN_BLANK, questionText: "They are ni_ _ years old.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/4-dt-17.jpg"), correctAnswer: "ne", explanation: "Nine: Số 9." },
    { id: 6, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["How", "mother", "today?", "is", "your"], correctAnswer: "How is your mother today?", explanation: "Hôm nay mẹ bạn thế nào?" },
    { id: 7, type: QuestionType.MULTIPLE_CHOICE, questionText: "Which is NOT mentioned in the recording?", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2018/1/4/636506591680339957_Audio.mp3"), options: ["bike", "train", "kite", "truck"], correctAnswer: "kite", explanation: "Nghe audio để xác định từ không được nhắc đến." },
    { id: 8, type: QuestionType.MULTIPLE_CHOICE, questionText: "Is ... house old? – Yes, it is.", options: ["it", "Nga", "her", "she"], correctAnswer: "her", explanation: "Her house: Nhà của cô ấy." },
    { id: 9, type: QuestionType.FILL_IN_BLANK, questionText: "What c_ _ ur is this? – It’s green.", correctAnswer: "olo", explanation: "Colour: Màu sắc." },
    { id: 10, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ _ da", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/11/30/636161005527331134_Audio.mp3"), correctAnswer: "Cana", explanation: "Canada." },
    { id: 11, type: QuestionType.MULTIPLE_CHOICE, questionText: "This is a ... desk.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206649526343286_566X320.jpg"), options: ["pink", "yellow", "blue", "green"], correctAnswer: "blue", explanation: "Nhìn tranh: Màu xanh dương." },
    { id: 12, type: QuestionType.MULTIPLE_CHOICE, questionText: "Stand up now and open ... book, Tom.", options: ["you", "your", "you’s", "you’re"], correctAnswer: "your", explanation: "Your book: Sách của bạn." },
    { id: 13, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["and new.", "large", "My bedroom", "is"], correctAnswer: "My bedroom is large and new.", explanation: "Phòng ngủ của tôi rộng và mới." },
    { id: 14, type: QuestionType.MULTIPLE_CHOICE, questionText: "What does he do during ... lessons? - He learns about numbers.", options: ["Maths", "English", "Arts", "Music"], correctAnswer: "Maths", explanation: "Learns about numbers (học về các con số) -> Maths." },
    { id: 15, type: QuestionType.MULTIPLE_CHOICE, questionText: "Come ..., please.", options: ["out", "in", "to", "under"], correctAnswer: "in", explanation: "Come in: Vào." },
    { id: 16, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["two dogs.", "a cat", "and", "My brother", "has"], correctAnswer: "My brother has a cat and two dogs.", explanation: "Anh tôi có 1 con mèo và 2 con chó." },
    { id: 17, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Who", "that?", "is"], correctAnswer: "Who is that?", explanation: "Kia là ai?" },
    { id: 18, type: QuestionType.MULTIPLE_CHOICE, questionText: "Goodbye Sally. See ... later.", options: ["hi", "my", "your", "you"], correctAnswer: "you", explanation: "See you later." },
    { id: 19, type: QuestionType.FILL_IN_BLANK, questionText: "This is Alice. _ _ _ is my friend.", correctAnswer: "She", explanation: "She is my friend." },
    { id: 20, type: QuestionType.FILL_IN_BLANK, questionText: "a_ _ le", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/11/30/636161051653206887_Audio.mp3"), correctAnswer: "pp", explanation: "Apple: Quả táo." },
    { id: 21, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["go out?", "me!", "Excuse", "I", "May"], correctAnswer: "Excuse me! May I go out?", explanation: "Xin lỗi, em có thể ra ngoài không?" },
    { id: 22, type: QuestionType.MULTIPLE_CHOICE, questionText: "... are you from, Jean? – I’m from Canada.", options: ["Where", "What", "How", "When"], correctAnswer: "Where", explanation: "Where are you from?" },
    { id: 23, type: QuestionType.FILL_IN_BLANK, questionText: "Happy birthday _ _ you, Alan. – Thank you.", correctAnswer: "to", explanation: "Happy birthday to you." },
    { id: 24, type: QuestionType.MULTIPLE_CHOICE, questionText: "Fine, ... .", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2018/11/30/636791922418973152_Audio.mp3"), options: ["thank", "thank you", "thanks", "thanks you"], correctAnswer: "thanks", explanation: "Fine, thanks." },
    { id: 25, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ ITE", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/3-dt-61.jpg"), correctAnswer: "WH", explanation: "WHITE: Màu trắng." },
    { id: 26, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ _ are you?", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206392417022931_Audio.mp3"), correctAnswer: "How", explanation: "How are you?" },
    { id: 27, type: QuestionType.FILL_IN_BLANK, questionText: "Goodbye, chi_ _ ren. See you later.", correctAnswer: "ld", explanation: "Children: Các em." },
    { id: 28, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the sentence that you hear:", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2019/11/29/637106244200733503_Audio.mp3"), options: ["How do you spell her name?", "How do you spell his name?", "How do you spell its name?", "How do you spell your name?"], correctAnswer: "How do you spell your name?", explanation: "Nghe audio." },
    { id: 29, type: QuestionType.FILL_IN_BLANK, questionText: "She doesn’t like ma_ _ ng paper boat.", correctAnswer: "ki", explanation: "Making." },
    { id: 30, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the odd one out:", options: ["Hello", "Hi", "Goodbye", "Green"], correctAnswer: "Green", explanation: "Green là màu sắc, còn lại là chào hỏi." },
    { id: 31, type: QuestionType.MULTIPLE_CHOICE, questionText: "Good ... , class.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Audio/3-tn-24.mp3"), options: ["afternoon", "evening", "morning", "bye"], correctAnswer: "afternoon", explanation: "Nghe audio." },
    { id: 32, type: QuestionType.MULTIPLE_CHOICE, questionText: "How are you? - ... .", options: ["I’m Binh", "She’s my sister", "I’m fine, thank you", "Goodbye"], correctAnswer: "I’m fine, thank you", explanation: "Trả lời sức khỏe." },
    { id: 33, type: QuestionType.FILL_IN_BLANK, questionText: "That is her n_ w school.", correctAnswer: "e", explanation: "New: Mới." },
    { id: 34, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["dancing.", "I", "Yes,", "like"], correctAnswer: "Yes, I like dancing.", explanation: "Vâng, tôi thích khiêu vũ." },
    { id: 35, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["What", "are", "those?"], correctAnswer: "What are those?", explanation: "Kia là những cái gì?" },
    { id: 36, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Put", "please.", "hands", "down,", "your"], correctAnswer: "Put your hands down, please.", explanation: "Hãy hạ tay xuống." },
    { id: 37, type: QuestionType.MULTIPLE_CHOICE, questionText: "... down, please!", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/1-tn-29.jpg"), options: ["Stand", "Get", "Close", "Sit"], correctAnswer: "Sit", explanation: "Sit down." },
    { id: 38, type: QuestionType.FILL_IN_BLANK, questionText: "_ EVEN", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/2-dt-31.jpg"), correctAnswer: "S", explanation: "SEVEN: Số 7." },
    { id: 39, type: QuestionType.FILL_IN_BLANK, questionText: "Wr_ _ _ the names in the blanks.", correctAnswer: "ite", explanation: "Write: Viết." },
    { id: 40, type: QuestionType.MULTIPLE_CHOICE, questionText: "... teacher is fine.", options: ["Me", "Her", "Him", "You"], correctAnswer: "Her", explanation: "Her teacher: Giáo viên của cô ấy (Tính từ sở hữu)." },
    { id: 41, type: QuestionType.FILL_IN_BLANK, questionText: "May I _ _ me in?", correctAnswer: "co", explanation: "Come in." },
    { id: 42, type: QuestionType.MULTIPLE_CHOICE, questionText: "Nice to meet ... , too .", options: ["me", "he", "your", "you"], correctAnswer: "you", explanation: "Nice to meet you too." },
    { id: 43, type: QuestionType.MULTIPLE_CHOICE, questionText: "Is this a school bag? - ... .", options: ["Yes, she is", "No, it isn’t", "Yes, I am", "No, he isn’t"], correctAnswer: "No, it isn’t", explanation: "Is this... -> Yes, it is / No, it isn't." },
    { id: 44, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["make", "mess.", "a", "Don’t"], correctAnswer: "Don’t make a mess.", explanation: "Đừng làm bừa bộn." },
    { id: 45, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the letter(s) to make a correct word: win _ ow", options: ["t", "d", "c", "h"], correctAnswer: "d", explanation: "Window: Cửa sổ." },
    { id: 46, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["English", "some", "songs.", "sing", "Let's"], correctAnswer: "Let's sing some English songs.", explanation: "Hãy hát vài bài tiếng Anh." },
    { id: 47, type: QuestionType.MULTIPLE_CHOICE, questionText: "A: Is that your classmate? - B: ...", options: ["Yes, he isn't.", "No, she isn’t.", "Yes, it is.", "No, I’m not."], correctAnswer: "Yes, it is.", explanation: "Is that... -> Yes, it is." },
    { id: 48, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["my", "Simon", "is", "friend.", "new"], correctAnswer: "Simon is my new friend.", explanation: "Simon là bạn mới của tôi." },
    { id: 49, type: QuestionType.FILL_IN_BLANK, questionText: "I_ is a crayon.", correctAnswer: "t", explanation: "It is." },
    { id: 50, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the incorrect word(s) in the following sentence: Those are my pencil.", options: ["Those", "are", "my", "pencil"], correctAnswer: "pencil", explanation: "Those are -> pencils (số nhiều)." },
    { id: 51, type: QuestionType.MULTIPLE_CHOICE, questionText: "Hello, ... Kate.", options: ["my name", "I", "I’m", "me"], correctAnswer: "I’m", explanation: "I'm Kate." },
    { id: 52, type: QuestionType.MULTIPLE_CHOICE, questionText: "How are you, Sandy? - ... .", options: ["I’m fine, thank", "Fine, thank", "Fine, thanks", "I fine, thank"], correctAnswer: "Fine, thanks", explanation: "Câu trả lời đúng ngữ pháp." },
    { id: 53, type: QuestionType.FILL_IN_BLANK, questionText: "This is my school _ _ _ .", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/23/635208313495743923_566X320.jpg"), correctAnswer: "bag", explanation: "School bag: Cặp sách." },
    { id: 54, type: QuestionType.FILL_IN_BLANK, questionText: "He is wearing an o_ _ _ _ _ T-shirt.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/12/16/636174950646374589_566X320.jpg"), correctAnswer: "range", explanation: "Orange: Màu cam." },
    { id: 55, type: QuestionType.FILL_IN_BLANK, questionText: "BA_ KPACK", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/2-dt-51.jpg"), correctAnswer: "C", explanation: "BACKPACK: Ba lô." },
    { id: 56, type: QuestionType.MULTIPLE_CHOICE, questionText: "What colour ... this?", options: ["it", "is", "that", "hi"], correctAnswer: "is", explanation: "What colour is this?" },
    { id: 57, type: QuestionType.MULTIPLE_CHOICE, questionText: "This ... a house.", options: ["are", "is", "you", "here"], correctAnswer: "is", explanation: "This is." },
    { id: 58, type: QuestionType.MULTIPLE_CHOICE, questionText: "I’m standing in a ... .", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206312811331111_Audio.mp3"), options: ["living room", "classroom", "room", "bedroom"], correctAnswer: "classroom", explanation: "Nghe audio." },
    { id: 59, type: QuestionType.MULTIPLE_CHOICE, questionText: "Who is this?", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/test/minigamet6/knight.jpg"), options: ["A prince", "A princess", "A knight", "A monster"], correctAnswer: "A knight", explanation: "A knight: Hiệp sĩ." },
    { id: 60, type: QuestionType.MULTIPLE_CHOICE, questionText: "I go to school library to ... books.", options: ["read’s", "reads", "read", "to read"], correctAnswer: "read", explanation: "To read books: Để đọc sách." },
    { id: 61, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ _ Mai and Hoa your friend?", correctAnswer: "Are", explanation: "Are Mai and Hoa..." },
    { id: 62, type: QuestionType.MULTIPLE_CHOICE, questionText: "... , I’m Lan.", options: ["Hi", "Goodbye!", "See you", "Goodnight!"], correctAnswer: "Hi", explanation: "Hi, I'm Lan." },
    { id: 63, type: QuestionType.FILL_IN_BLANK, questionText: "That is a br_ _ n book.", correctAnswer: "ow", explanation: "Brown: Màu nâu." },
    { id: 64, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["my", "friend", "This", ", Peter.", "is"], correctAnswer: "This is my friend, Peter.", explanation: "Đây là bạn tôi, Peter." },
    { id: 65, type: QuestionType.MULTIPLE_CHOICE, questionText: "The pencils are ... my pencil case.", options: ["in", "on", "at", "of"], correctAnswer: "in", explanation: "In: Ở trong." },
    { id: 66, type: QuestionType.MULTIPLE_CHOICE, questionText: "I ... watching television.", options: ["is", "are", "am", "aren’t"], correctAnswer: "am", explanation: "I am." },
    { id: 67, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["May", "I", "you", "your name?", "ask"], correctAnswer: "May I ask you your name?", explanation: "Tôi có thể hỏi tên bạn không?" },
    { id: 68, type: QuestionType.MULTIPLE_CHOICE, questionText: "A: Do you like skating or skipping? - B: …", options: ["Yes, I do.", "No, I don’t.", "I like skipping.", "I skip at break time."], correctAnswer: "I like skipping.", explanation: "Câu hỏi lựa chọn (or) -> Trả lời sự lựa chọn." },
    { id: 69, type: QuestionType.FILL_IN_BLANK, questionText: "Let’s co_ nt the boys.", correctAnswer: "u", explanation: "Count: Đếm." },
    { id: 70, type: QuestionType.FILL_IN_BLANK, questionText: "Peter is my friend, t_ _ .", correctAnswer: "oo", explanation: "Too: Cũng vậy." },
    { id: 71, type: QuestionType.FILL_IN_BLANK, questionText: "Where _ _ your cat?", correctAnswer: "is", explanation: "Where is." },
    { id: 72, type: QuestionType.MULTIPLE_CHOICE, questionText: "What’s ... name?", options: ["she", "he", "you", "her"], correctAnswer: "her", explanation: "Her name: Tên cô ấy." },
    { id: 73, type: QuestionType.FILL_IN_BLANK, questionText: "Sit d_ _ _ , Tommy.", correctAnswer: "own", explanation: "Down." },
    { id: 74, type: QuestionType.MULTIPLE_CHOICE, questionText: "Hi, I’m Richard. Nice ... meet you.", options: ["to", "at", "on", "in"], correctAnswer: "to", explanation: "Nice to meet you." },
    { id: 75, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["she", "Is", "your sister?"], correctAnswer: "Is she your sister?", explanation: "Cô ấy có phải chị bạn không?" },
    { id: 76, type: QuestionType.FILL_IN_BLANK, questionText: "Is this a d_ sk? - Yes, it is.", correctAnswer: "e", explanation: "Desk: Cái bàn." },
    { id: 77, type: QuestionType.MULTIPLE_CHOICE, questionText: "This is my new ….", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2018/1/4/636506590721587840_Audio.mp3"), options: ["pencil", "pencil case", "rubber", "pencil sharpener"], correctAnswer: "pencil case", explanation: "Nghe audio." },
    { id: 78, type: QuestionType.FILL_IN_BLANK, questionText: "That is my fr_ _ nd.", correctAnswer: "ie", explanation: "Friend: Bạn." },
    { id: 79, type: QuestionType.FILL_IN_BLANK, questionText: "TEA_ _ ER", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/4-dt-50.jpg"), correctAnswer: "CH", explanation: "TEACHER: Giáo viên." },
    { id: 80, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["is", "friend", "very nice.", "new", "My"], correctAnswer: "My new friend is very nice.", explanation: "Bạn mới của tôi rất tốt bụng." },
    { id: 81, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ _ t’s your name? – My name’s Tom.", correctAnswer: "Wha", explanation: "What's your name." },
    { id: 82, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["answer,", "the", "Circle", "children."], correctAnswer: "Circle the answer, children.", explanation: "Hãy khoanh vào đáp án, các em." },
    { id: 83, type: QuestionType.FILL_IN_BLANK, questionText: "Circle the an_ _ er.", correctAnswer: "sw", explanation: "Answer: Câu trả lời." },
    { id: 84, type: QuestionType.MULTIPLE_CHOICE, questionText: "A: This is my school. - B: ….", options: ["Wow! It’s very nice.", "I’m fine, thanks.", "Let’s go.", "I don’t like it."], correctAnswer: "Wow! It’s very nice.", explanation: "Lời khen ngợi." },
    { id: 85, type: QuestionType.MULTIPLE_CHOICE, questionText: "What do you do in … free time?", options: ["you", "yours", "you’re", "your"], correctAnswer: "your", explanation: "Your free time." },
    { id: 86, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["any", "Are there", "your bedroom?", "in", "books"], correctAnswer: "Are there any books in your bedroom?", explanation: "Có quyển sách nào trong phòng ngủ của bạn không?" },
    { id: 87, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ _ are you? - Fine, thanks.", correctAnswer: "How", explanation: "How are you." },
    { id: 88, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["See", "tomorrow.", "Goodbye.", "you"], correctAnswer: "Goodbye. See you tomorrow.", explanation: "Tạm biệt. Hẹn gặp lại ngày mai." },
    { id: 89, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ _ _", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2018/11/30/636791933023039557_566X320.jpg"), correctAnswer: "book", explanation: "Book: Quyển sách." },
    { id: 90, type: QuestionType.MULTIPLE_CHOICE, questionText: "I have Art ... Friday.", options: ["in", "at", "to", "on"], correctAnswer: "on", explanation: "On + Thứ trong tuần." },
    { id: 91, type: QuestionType.FILL_IN_BLANK, questionText: "The f_ _ _ is in the bottle.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/23/635208369486521798_566X320.jpg"), correctAnswer: "ish", explanation: "Fish: Con cá." },
    { id: 92, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["is", "your", "What", "name?"], correctAnswer: "What is your name?", explanation: "Tên bạn là gì?" },
    { id: 93, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["This", "a", "pen.", "is"], correctAnswer: "This is a pen.", explanation: "Đây là một cái bút." },
    { id: 94, type: QuestionType.FILL_IN_BLANK, questionText: "Please, _ _ _ down.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2018/1/2/636505039668603115_566X320.jpg"), correctAnswer: "sit", explanation: "Sit down." },
    { id: 95, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["a book", "I have", "my bag.", "in"], correctAnswer: "I have a book in my bag.", explanation: "Tôi có một quyển sách trong cặp." },
    { id: 96, type: QuestionType.FILL_IN_BLANK, questionText: "Anna doesn’t play skipping at br_ _ _ time.", correctAnswer: "eak", explanation: "Break time: Giờ ra chơi." },
    { id: 97, type: QuestionType.MULTIPLE_CHOICE, questionText: "BAD_INTON", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/2-tn-51.jpg"), options: ["M", "N", "T", "D"], correctAnswer: "M", explanation: "BADMINTON: Cầu lông." },
    { id: 98, type: QuestionType.FILL_IN_BLANK, questionText: "Be q_ iet , boys!", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/2-dt-40.jpg"), correctAnswer: "u", explanation: "Quiet: Trật tự." },
    { id: 99, type: QuestionType.MULTIPLE_CHOICE, questionText: "There is ... dog in my house.", options: ["a", "are", "two", "is"], correctAnswer: "a", explanation: "A dog (số ít)." },
    { id: 100, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["sentences", "Reorder", "the", ", please."], correctAnswer: "Reorder the sentences, please.", explanation: "Hãy sắp xếp lại câu." },
    { id: 101, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Put", "hand", "your", "down."], correctAnswer: "Put your hand down.", explanation: "Hạ tay xuống." },
    { id: 102, type: QuestionType.FILL_IN_BLANK, questionText: "Is that you_ friend?", correctAnswer: "r", explanation: "Your." },
    { id: 103, type: QuestionType.FILL_IN_BLANK, questionText: "My school is near _ bakery.", correctAnswer: "a", explanation: "A bakery." },
    { id: 104, type: QuestionType.FILL_IN_BLANK, questionText: "_ play basketball.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Audio/4-dt-7.mp3"), correctAnswer: "I", explanation: "I play basketball." },
    { id: 105, type: QuestionType.MULTIPLE_CHOICE, questionText: "There are … people in her family.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/11/30/636161037411460282_Audio.mp3"), options: ["seven", "six", "five", "eight"], correctAnswer: "five", explanation: "Nghe audio." },
    { id: 106, type: QuestionType.MULTIPLE_CHOICE, questionText: "Nice … meet you, Susan.", options: ["too", "to", "two", "toe"], correctAnswer: "to", explanation: "Nice to meet you." },
    { id: 107, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["are", "Peter’s", "pencil", "Those", "cases."], correctAnswer: "Those are Peter’s pencil cases.", explanation: "Kia là những hộp bút của Peter." },
    { id: 108, type: QuestionType.FILL_IN_BLANK, questionText: "W_ _ is he? – He is my best friend.", correctAnswer: "ho", explanation: "Who: Ai." },
    { id: 109, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Peter.", "you,", "Thank"], correctAnswer: "Thank you, Peter.", explanation: "Cảm ơn bạn, Peter." },
    { id: 110, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["please!", "and", "Sit down", "your book,", "open"], correctAnswer: "Sit down and open your book, please!", explanation: "Ngồi xuống và mở sách ra nào." },
    { id: 111, type: QuestionType.MULTIPLE_CHOICE, questionText: "Pick … your pencil.", options: ["at", "up", "on", "for"], correctAnswer: "up", explanation: "Pick up: Nhặt lên." },
    { id: 112, type: QuestionType.MULTIPLE_CHOICE, questionText: "It is ... desk.", options: ["an", "a", "two", "you"], correctAnswer: "a", explanation: "A desk." },
    { id: 113, type: QuestionType.FILL_IN_BLANK, questionText: "This is a b_ cycle.", correctAnswer: "i", explanation: "Bicycle: Xe đạp." },
    { id: 114, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["This", "is", "school", "my", "bus."], correctAnswer: "This is my school bus.", explanation: "Đây là xe buýt trường tôi." },
    { id: 115, type: QuestionType.FILL_IN_BLANK, questionText: "Come ov_ r here.", correctAnswer: "e", explanation: "Over." },
    { id: 116, type: QuestionType.MULTIPLE_CHOICE, questionText: "This isn’t ... bag.", options: ["he", "his", "me", "you"], correctAnswer: "his", explanation: "His bag: Cặp của cậu ấy." },
    { id: 117, type: QuestionType.FILL_IN_BLANK, questionText: "Listen _ _ your friends, please.", correctAnswer: "to", explanation: "Listen to." },
    { id: 118, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["my school bag.", "There are", "pencils", "ten", "in"], correctAnswer: "There are ten pencils in my school bag.", explanation: "Có 10 cái bút chì trong cặp tôi." },
    { id: 119, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the incorrect word(s) in the following sentence: These are my notebook.", options: ["These", "are", "my", "notebook"], correctAnswer: "notebook", explanation: "These are -> notebooks (số nhiều)." },
    { id: 120, type: QuestionType.FILL_IN_BLANK, questionText: "LIBRAR_", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/1-dt-54.jpg"), correctAnswer: "Y", explanation: "LIBRARY: Thư viện." },
    { id: 121, type: QuestionType.FILL_IN_BLANK, questionText: "What is her j_ _ ? – She is a teacher.", correctAnswer: "ob", explanation: "Job: Nghề nghiệp." },
    { id: 122, type: QuestionType.FILL_IN_BLANK, questionText: "Emma doesn’t like playing _ _ _ _ _ .", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2018/1/2/636505050517276971_Audio.mp3"), correctAnswer: "chess", explanation: "Nghe audio." },
    { id: 123, type: QuestionType.MULTIPLE_CHOICE, questionText: "Hello, ... name is Scott.", options: ["he", "she", "it", "my"], correctAnswer: "my", explanation: "My name." },
    { id: 124, type: QuestionType.MULTIPLE_CHOICE, questionText: "A: May I ask a question, Miss Nga? - B: Yes, you ...", options: ["may", "can", "are", "do"], correctAnswer: "may", explanation: "Yes, you may." },
    { id: 125, type: QuestionType.FILL_IN_BLANK, questionText: "Miss Lan is my new t_ _ _ her.", correctAnswer: "eac", explanation: "Teacher: Giáo viên." },
    { id: 126, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the odd one out:", options: ["fine", "read", "meet", "play"], correctAnswer: "fine", explanation: "Fine là tính từ, còn lại là động từ." },
    { id: 127, type: QuestionType.FILL_IN_BLANK, questionText: "Si_ down!", correctAnswer: "t", explanation: "Sit down." },
    { id: 128, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ n't be late!", correctAnswer: "Do", explanation: "Don't be late." },
    { id: 129, type: QuestionType.FILL_IN_BLANK, questionText: "The rain_ _ _ is beautiful.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/22/635207385740095170_566X320.jpg"), correctAnswer: "bow", explanation: "Rainbow: Cầu vồng." },
    { id: 130, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Clean", "your", "teeth", ", please."], correctAnswer: "Clean your teeth, please.", explanation: "Hãy đánh răng đi." },
    { id: 131, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Don’t", "make", "a", "mess."], correctAnswer: "Don’t make a mess.", explanation: "Đừng làm bừa bộn." },
    { id: 132, type: QuestionType.MULTIPLE_CHOICE, questionText: "Listen and tick:", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206374977284300_Audio.mp3"), options: ["There are two bathrooms.", "There are three bedrooms.", "There are two bedrooms.", "There are two living rooms."], correctAnswer: "There are two bathrooms.", explanation: "Nghe audio." },
    { id: 133, type: QuestionType.MULTIPLE_CHOICE, questionText: "This is Tom and that … Mary.", options: ["am", "is", "are", "have"], correctAnswer: "is", explanation: "That is." },
    { id: 134, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["apple.", "This", "is", "a", "red"], correctAnswer: "This is a red apple.", explanation: "Đây là quả táo màu đỏ." },
    { id: 135, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ _ you happy today? - Yes, I am.", correctAnswer: "Are", explanation: "Are you." },
    { id: 136, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["is", "old", "brother?", "your", "How"], correctAnswer: "How old is your brother?", explanation: "Anh bạn bao nhiêu tuổi?" },
    { id: 137, type: QuestionType.FILL_IN_BLANK, questionText: "Is it _ ruler? – No, it isn’t.", correctAnswer: "a", explanation: "A ruler." },
    { id: 138, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["What", "time", "the", "now?", "is"], correctAnswer: "What is the time now?", explanation: "Bây giờ là mấy giờ?" },
    { id: 139, type: QuestionType.MULTIPLE_CHOICE, questionText: "What do you do at break time? – I ... .", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206495934558641_566X320.jpg"), options: ["play tennis", "play football", "play chess", "swim"], correctAnswer: "play football", explanation: "Nhìn tranh: Đá bóng." },
    { id: 140, type: QuestionType.FILL_IN_BLANK, questionText: "SCHO_ L", correctAnswer: "O", explanation: "SCHOOL: Trường học." },
    { id: 141, type: QuestionType.FILL_IN_BLANK, questionText: "Goodbye. See you tomorr_ w.", correctAnswer: "o", explanation: "Tomorrow." },
    { id: 142, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["name", "Write", "please.", "your", "here,"], correctAnswer: "Write your name here, please.", explanation: "Hãy viết tên bạn vào đây." },
    { id: 143, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["my", "These", "notebooks", "are", "and pencils."], correctAnswer: "These are my notebooks and pencils.", explanation: "Đây là vở và bút chì của tôi." },
    { id: 144, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["I have", "a glass of juice?", "May"], correctAnswer: "May I have a glass of juice?", explanation: "Cho em một ly nước ép được không?" },
    { id: 145, type: QuestionType.MULTIPLE_CHOICE, questionText: "What’s his name?", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2018/11/30/636791931490240996_Audio.mp3"), options: ["Pitir", "Peter", "Beter", "Bitia"], correctAnswer: "Peter", explanation: "Nghe audio." },
    { id: 146, type: QuestionType.FILL_IN_BLANK, questionText: "This is my new bicycle. – O_ , it’s very nice.", correctAnswer: "h", explanation: "Oh." },
    { id: 147, type: QuestionType.FILL_IN_BLANK, questionText: "Sally has bl_ _ eyes and blonde hair.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/12/16/636174948921681281_566X320.jpg"), correctAnswer: "ue", explanation: "Blue eyes: Mắt xanh." },
    { id: 148, type: QuestionType.MULTIPLE_CHOICE, questionText: "This is ... desk.", options: ["an", "he", "he’s", "a"], correctAnswer: "a", explanation: "A desk." },
    { id: 149, type: QuestionType.FILL_IN_BLANK, questionText: "What’s h_ _ name? – She is Hoa.", correctAnswer: "er", explanation: "Her name: Tên cô ấy." },
    { id: 150, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["stand", "please.", "Let's", "up,"], correctAnswer: "Let's stand up, please.", explanation: "Hãy đứng lên." },
    { id: 151, type: QuestionType.MULTIPLE_CHOICE, questionText: "How ... is she? – She’s nine years old.", options: ["years", "and", "but", "old"], correctAnswer: "old", explanation: "How old." },
    { id: 152, type: QuestionType.FILL_IN_BLANK, questionText: "My school _ _ new.", correctAnswer: "is", explanation: "Is." },
    { id: 153, type: QuestionType.MULTIPLE_CHOICE, questionText: "What is your ...? – I’m Peter.", options: ["name", "name’s", "meet", "friend"], correctAnswer: "name", explanation: "What is your name?" },
    { id: 154, type: QuestionType.FILL_IN_BLANK, questionText: "Is this a pen? - _ _ _ , it is.", correctAnswer: "Yes", explanation: "Yes, it is." },
    { id: 155, type: QuestionType.MULTIPLE_CHOICE, questionText: "- Hello, Lan. - ...", options: ["Bye, Phuong.", "Good night, Phuong.", "Hi, Phuong.", "Yes, you."], correctAnswer: "Hi, Phuong.", explanation: "Đáp lại lời chào Hello là Hi/Hello." },
    { id: 156, type: QuestionType.FILL_IN_BLANK, questionText: "How m_ _ y pens do you have?", correctAnswer: "an", explanation: "Many." },
    { id: 157, type: QuestionType.FILL_IN_BLANK, questionText: "I like skipp_ _ _ .", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Audio/1-dt-62.mp3"), correctAnswer: "ing", explanation: "Skipping: Nhảy dây." },
    { id: 158, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the sentence that you hear:", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2019/11/29/637106245677285569_Audio.mp3"), options: ["This is Peter. And that’s Tony.", "That’s Peter. And that’s Tony.", "That’s Peter. And that’s Mary.", "That’s Tony. And that’s Mary."], correctAnswer: "That’s Peter. And that’s Tony.", explanation: "Nghe audio." },
    { id: 159, type: QuestionType.FILL_IN_BLANK, questionText: "Po_ _ t to the teacher.", correctAnswer: "in", explanation: "Point: Chỉ vào." },
    { id: 160, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["playing", "football.", "They", "are"], correctAnswer: "They are playing football.", explanation: "Họ đang đá bóng." },
    { id: 161, type: QuestionType.FILL_IN_BLANK, questionText: "This is Tom. _ _ is my friend.", correctAnswer: "He", explanation: "He is." },
    { id: 162, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the letter(s) to make a correct word: sk _ te", options: ["a", "e", "o", "u"], correctAnswer: "a", explanation: "Skate: Trượt băng." },
    { id: 163, type: QuestionType.MULTIPLE_CHOICE, questionText: "Sing a ..., please.", options: ["you", "me", "song", "he"], correctAnswer: "song", explanation: "Sing a song: Hát một bài." },
    { id: 164, type: QuestionType.FILL_IN_BLANK, questionText: "That is a blue s_ _ _ .", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/23/635208321994581633_566X320.jpg"), correctAnswer: "ock", explanation: "Sock: Chiếc tất." },
    { id: 165, type: QuestionType.FILL_IN_BLANK, questionText: "Good ev_ _ ing, Tom.", correctAnswer: "en", explanation: "Evening." },
    { id: 166, type: QuestionType.MULTIPLE_CHOICE, questionText: "How ... robots are there?", options: ["many", "much", "any", "very"], correctAnswer: "many", explanation: "How many." },
    { id: 167, type: QuestionType.FILL_IN_BLANK, questionText: "b_ g", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/11/30/636161052058989367_Audio.mp3"), correctAnswer: "a", explanation: "Bag." },
    { id: 168, type: QuestionType.FILL_IN_BLANK, questionText: "I want to st_ y at home.", correctAnswer: "a", explanation: "Stay." },
    { id: 169, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ y I go out? – Yes, please.", correctAnswer: "Ma", explanation: "May I." },
    { id: 170, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["my bag.", "The books", "in", "are"], correctAnswer: "The books are in my bag.", explanation: "Sách ở trong cặp tôi." },
    { id: 171, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["in", "is", "the blue T-shirt", "my brother.", "The boy"], correctAnswer: "The boy in the blue T-shirt is my brother.", explanation: "Cậu bé mặc áo phông xanh là anh tôi." },
    { id: 172, type: QuestionType.MULTIPLE_CHOICE, questionText: "This is ... chair.", options: ["he", "she", "it", "my"], correctAnswer: "my", explanation: "My chair." },
    { id: 173, type: QuestionType.FILL_IN_BLANK, questionText: "I'm _ _ ven.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Audio/3-dt-35.mp3"), correctAnswer: "se", explanation: "Seven: Số 7." },
    { id: 174, type: QuestionType.MULTIPLE_CHOICE, questionText: "It’s ... ball.", options: ["a", "an", "two", "Ø"], correctAnswer: "a", explanation: "A ball." },
    { id: 175, type: QuestionType.FILL_IN_BLANK, questionText: "This is m_ blue book.", correctAnswer: "y", explanation: "My." },
    { id: 176, type: QuestionType.FILL_IN_BLANK, questionText: "H_ _ are you? – I’m fine, thanks.", correctAnswer: "ow", explanation: "How are you." },
    { id: 177, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["That", "box.", "my", "is"], correctAnswer: "That is my box.", explanation: "Đó là hộp của tôi." },
    { id: 178, type: QuestionType.MULTIPLE_CHOICE, questionText: "They ... in the living room.", options: ["are", "is", "am", "on"], correctAnswer: "are", explanation: "They are." },
    { id: 179, type: QuestionType.FILL_IN_BLANK, questionText: "Her _ _ _ _ is small.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/23/635208372081274355_566X320.jpg"), correctAnswer: "hand", explanation: "Hand: Bàn tay." },
    { id: 180, type: QuestionType.FILL_IN_BLANK, questionText: "Her _ _ _ _ is small.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/22/635207376510514039_566X320.jpg"), correctAnswer: "nose", explanation: "Nose: Cái mũi." },
    { id: 181, type: QuestionType.MULTIPLE_CHOICE, questionText: "... and write.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Audio/4-tn-25.mp3"), options: ["Read", "Look", "Listen", "Point"], correctAnswer: "Read", explanation: "Nghe audio: Read and write." },
    { id: 182, type: QuestionType.FILL_IN_BLANK, questionText: "Hi, how _ _ _ you?", correctAnswer: "are", explanation: "How are you." },
    { id: 183, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["is", "pretty.", "Mary", "very"], correctAnswer: "Mary is very pretty.", explanation: "Mary rất xinh đẹp." },
    { id: 184, type: QuestionType.MULTIPLE_CHOICE, questionText: "Listen and tick:", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206377131960084_Audio.mp3"), options: ["My father is a teacher.", "My mother is a teacher", "My father is a doctor.", "My brother is a teacher."], correctAnswer: "My father is a teacher.", explanation: "Nghe audio." },
    { id: 185, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["She", "old.", "ten", "years", "is"], correctAnswer: "She is ten years old.", explanation: "Cô ấy 10 tuổi." },
    { id: 186, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ _ t colour is this? – It’s pink.", correctAnswer: "Wha", explanation: "What colour." },
    { id: 187, type: QuestionType.MULTIPLE_CHOICE, questionText: "This is ... orange pen.", options: ["an", "a", "the", "this"], correctAnswer: "an", explanation: "An orange pen (nguyên âm)." },
    { id: 188, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["old.", "years", "seven", "I’m"], correctAnswer: "I’m seven years old.", explanation: "Tôi 7 tuổi." },
    { id: 189, type: QuestionType.MULTIPLE_CHOICE, questionText: "Would you like some milk? – Yes, ... .", options: ["his", "please", "this", "is"], correctAnswer: "please", explanation: "Yes, please." },
    { id: 190, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["the school gate.", "Peter and Mary", "are", "at"], correctAnswer: "Peter and Mary are at the school gate.", explanation: "Peter và Mary đang ở cổng trường." },
    { id: 191, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the odd one out:", options: ["classroom", "bedroom", "bathroom", "living room"], correctAnswer: "classroom", explanation: "Classroom ở trường, còn lại là phòng trong nhà." },
    { id: 192, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ o is that? – That’s Mary.", correctAnswer: "Wh", explanation: "Who is that." },
    { id: 193, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ ese are my pencil boxes.", correctAnswer: "Th", explanation: "These." },
    { id: 194, type: QuestionType.MULTIPLE_CHOICE, questionText: "We go to school to ... .", options: ["stay", "study", "sit", "go"], correctAnswer: "study", explanation: "To study: Để học." },
    { id: 195, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["is", "That", "apple.", "red", "a"], correctAnswer: "That is a red apple.", explanation: "Kia là một quả táo đỏ." },
    { id: 196, type: QuestionType.MULTIPLE_CHOICE, questionText: "What is this? – It is … eraser.", options: ["a", "an", "this", "that"], correctAnswer: "an", explanation: "An eraser." },
    { id: 197, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["down", "Copy", "the", "words."], correctAnswer: "Copy down the words.", explanation: "Chép các từ xuống." },
    { id: 198, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Henry.", "pens,", "out", "your", "Take"], correctAnswer: "Take out your pens, Henry.", explanation: "Lấy bút ra nào Henry." },
    { id: 199, type: QuestionType.MULTIPLE_CHOICE, questionText: "I’m fine, thank you. ... ?", options: ["You", "And you", "Are", "Bye"], correctAnswer: "And you", explanation: "Hỏi lại: Còn bạn thì sao?" },
    { id: 200, type: QuestionType.FILL_IN_BLANK, questionText: "Thank you very m_ _ h.", correctAnswer: "uc", explanation: "Very much." }
];
